# DbConstants.py
TABLE_USER = "user"
TABLE_ROLE = "role"
TABLE_ROLE_USERS = "roles_users"
TABLE_SESSION_LOG = "session_log"
TABLE_EMPLOYEE_LOG = "employee_log"

TEXT_LENGTH_PRIMARY = 255
TEXT_LENGTH_DESCRIPTION_PRIMARY = 400
TEXT_LENGTH_DESCRIPTION_SECONDARY = 200
